import { faArrowDownFromBracket } from '@fortawesome/pro-solid-svg-icons';

export const moofyToWalmartRoutes = {
  2: [
    { name: '979', location: 'PALI FRAIJANES' },
    { name: '3139', location: 'PALI POAS' },
  ],
  4: [
    { name: '762', location: 'PALI SABANA GRANDE' },
    { name: '3125', location: 'PALI ATENAS' },
    { name: '4339', location: 'MAXI ATENAS' },
  ],
  5: [
    { name: '778', location: 'MAXI MONTECILLOS' },
    { name: '939', location: 'MAXI ALAJUELA ESTE' },
    { name: '978', location: 'MAXI SAN PABLO' },
    { name: '988', location: 'MAXI LAGUNILLA' },
    { name: '990', location: 'PALI SANTA ROSA' },
    { name: '1008', location: 'MAXI SAN RAFAEL HEREDIA' },
    { name: '1012', location: 'PALI MIRAFLORES' },
    { name: '1015', location: 'PALI SAN LUIS SANTO DOMINGO' },
    { name: '1026', location: 'PALI EL ROBLE SANTA BARBARA' },
    { name: '3031', location: 'MXM ALAJUELA' },
    { name: '3036', location: 'MXM HEREDIA' },
    { name: '3037', location: 'MXM SAN PABLO' },
    { name: '3041', location: 'MXM ALAJUELA CENTRO' },
    { name: '3044', location: 'MXM PASEO DE LAS FLORES' },
    { name: '3053', location: 'PALI STO.DOMINGO' },
    { name: '3056', location: 'PALI ALAJUELA' },
    { name: '3063', location: 'PALI HEREDIA' },
    { name: '3084', location: 'PALI EL LLANO' },
    { name: '3089', location: 'PALI AURORA' },
    { name: '3090', location: 'PALI BELEN' },
    { name: '3091', location: 'PALI BARVA' },
    { name: '3102', location: 'PALI UNICENTRO' },
    { name: '3112', location: 'MAXI PACIFICO' },
    { name: '3115', location: 'PALI HEREDIA CENTRO' },
    { name: '3120', location: 'PALI SAN JOAQUIN' },
    { name: '3121', location: 'PALI BARRIO SAN JOSE' },
    { name: '3142', location: 'PALI SANTA BARBARA' },
    { name: '3145', location: 'PALI SAN RAFAEL HEREDIA' },
    { name: '3701', location: 'WM HEREDIA' },
    { name: '3901', location: 'MAXI ALAJUELA' },
    { name: '4084', location: 'PALI SAN ISIDRO HEREDIA' },
    { name: '4118', location: 'PALI SAN PABLO' },
    { name: '4253', location: 'WM ALAJUELA' },
    { name: '4261', location: 'PALI SAN MIGUEL SANTO DOMINGO' },
    { name: '4279', location: 'PALI PARQUE CENTRAL BARVA' },
    { name: '4281', location: 'PALI MERCEDES SUR' },
    { name: '4318', location: 'MAXI MERCEDES NORTE' },
    { name: '4404', location: 'MXM HEREDIA SUR' },
    { name: '4426', location: 'MXM SAN JOAQUIN' },
    { name: '4430', location: 'MXM BARRIO SAN JOSE' },
    { name: '4431', location: 'MXM SAN PABLO NORTE' },
    { name: '4444', location: 'PALI SAN PEDRO DE BARVA' },
    { name: '4461', location: 'MP SANTA BARBARA' },
  ],
  6: [
    { name: '4258', location: 'MAXI RIO CLARO' },
    { name: '737', location: 'PALI PUERTO JIMENEZ' },
    { name: '4170', location: 'PALI SAN VITO COTO BRUS' },
    { name: '4059', location: 'PALI RIO CLARO' },
    { name: '3105', location: 'PALI CIUDAD NEILY' },
  ],
  7: [
    { name: '829', location: 'WM PEREZ ZELEDON' },
    { name: '953', location: 'PALI LA CUESTA' },
    { name: '966', location: 'MAXI UVITA' },
    { name: '1036', location: 'PALI GENERAL VIEJO' },
    { name: '1037', location: 'PALI GOLFITO' },
    { name: '1058', location: 'PALI CAJON' },
    { name: '1061', location: 'PALI CIUDAD CORTES' },
    { name: '3064', location: 'PALI SAN ISIDRO' },
    { name: '4003', location: 'PALI PALMAR NORTE' },
    { name: '4030', location: 'MAXI PEREZ ZELEDON' },
    { name: '4063', location: 'PALI BUENOS AIRES' },
  ],

  8: [
    { name: '749', location: 'PALI PACAYAS' },
    { name: '786', location: 'PALI LA SUIZA' },
    { name: '793', location: 'MAXI TURRIALBA NORTE' },
    { name: '852', location: 'PALI OROSI' },
    { name: '917', location: 'PALI CERVANTES' },
    { name: '967', location: 'PALI JUAN VINAS' },
    { name: '1000', location: 'PALI TUCURRIQUE' },
    { name: '1035', location: 'PALI SANTA ROSA TURRIALBA' },
    { name: '1038', location: 'PALI OREAMUNO' },
    { name: '3076', location: 'PALI TURRIALBA' },
    { name: '3078', location: 'PALI PARAISO' },
    { name: '3123', location: 'PALI SANTA LUCIA' },
    { name: '3136', location: 'PALI COT' },
    { name: '4099', location: 'MAXI TURRIALBA' },
    { name: '4256', location: 'PALI TIERRA BLANCA' },
  ],

  9: [
    { name: '950', location: 'PALI SANTA MARIA DE DOTA' },
    { name: '1018', location: 'PALI CORRALILLO' },
    { name: '1063', location: 'PALI SAN PABLO LEON CORTES' },
    { name: '1086', location: 'PALI PALMICHAL' },
    { name: '3108', location: 'PALI PURISCAL' },
    { name: '4083', location: 'PALI TARRAZU' },
    { name: '4157', location: 'PALI VUELTA DE JORCO' },
    { name: '4390', location: 'MAXI PURISCAL' },
  ],

  10: [
    { name: '700', location: 'WM LIBERIA' },
    { name: '828', location: 'MAXI UPALA' },
    { name: '934', location: 'PALI GUAYABO' },
    { name: '958', location: 'MAXI PLAYAS DEL COCO' },
    { name: '1006', location: 'PALI BIJAGUA' },
    { name: '1020', location: 'PALI COMUNIDAD' },
    { name: '1089', location: 'MXM LIBERIA' },
    { name: '1118', location: 'LIBERIA ESTADIO' },
    { name: '3065', location: 'PALI LIBERIA' },
    { name: '3093', location: 'PALI CANAS' },
    { name: '3124', location: 'PALI TILARAN' },
    { name: '3905', location: 'MAXI LIBERIA' },
    { name: '4026', location: 'PALI UPALA' },
    { name: '4052', location: 'PALI SARDINAL' },
    { name: '4060', location: 'PALI LA CRUZ' },
    { name: '4081', location: 'PALI BAGACES' },
    { name: '4125', location: 'PALI FILADELFIA' },
    { name: '4188', location: 'PALI SAN ROQUE LIBERIA' },
    { name: '4195', location: 'MAXI CANAS' },
  ],

  11: [
    { name: '729', location: 'PALI MATINA' },
    { name: '909', location: 'PALI LIMONCITO' },
    { name: '994', location: 'PALI CORALES' },
    { name: '3039', location: 'MXM LIMON' },
    { name: '3094', location: 'PALI LIMON' },
    { name: '3904', location: 'MAXI LIMON' },
    { name: '4124', location: 'PALI BATAAN' },
    { name: '4181', location: 'PALI PUERTO VIEJO' },
  ],

  12: [
    { name: '711', location: 'PALI LA RITA' },
    { name: '720', location: 'PALI JIMENEZ' },
    { name: '851', location: 'PALI RIO JIMENEZ' },
    { name: '961', location: 'PALI POCORA' },
    { name: '965', location: 'MAXI CARIARI' },
    { name: '1001', location: 'PALI LA VIRGEN DE SARAPIQUI' },
    { name: '3038', location: 'MXM GUAPILES' },
    { name: '3073', location: 'PALI GUAPILES' },
    { name: '3101', location: 'PALI SIQUIRRES' },
    { name: '3110', location: 'PALI CARIARI' },
    { name: '3128', location: 'PALI GUACIMO' },
    { name: '3143', location: 'PALI RIO FRIO' },
    { name: '4000', location: 'PALI SARAPIQUI' },
    { name: '4136', location: 'MAXI GUAPILES' },
    { name: '4369', location: 'MAXI SIQUIRRES' },
  ],

  13: [
    { name: '763', location: 'PALI JACO' },
    { name: '908', location: 'PALI LA INMACULADA' },
    { name: '1062', location: 'PALI MONTEVERDE' },
    { name: '3040', location: 'MXM JACO' },
    { name: '3109', location: 'PALI PARRITA' },
    { name: '3127', location: 'PALI QUEPOS' },
    { name: '4029', location: 'MAXI JACO' },
    { name: '4128', location: 'PALI LAS JUNTAS' },
    { name: '4166', location: 'PALI MIRAMAR' },
    { name: '4215', location: 'MAXI QUEPOS' },
    { name: '4486', location: 'MAXI PARRITA' },
  ],

  14: [
    { name: '768', location: 'WM CIUDAD QUESADA' },
    { name: '781', location: 'PALI VENECIA' },
    { name: '785', location: 'PALI SANTA CLARA' },
    { name: '827', location: 'MAXI LA FORTUNA' },
    { name: '1028', location: 'PALI LOS ANGELES LA FORTUNA' },
    { name: '1055', location: 'PALI CIUDAD QUESADA NORTE' },
    { name: '3069', location: 'PALI CIUDAD QUESADA' },
    { name: '3130', location: 'PALI PITAL' },
    { name: '3144', location: 'PALI FLORENCIA' },
    { name: '3903', location: 'MAXI CIUDAD QUESADA' },
    { name: '4020', location: 'PALI LOS CHILES' },
    { name: '4021', location: 'PALI GUATUSO' },
    { name: '4088', location: 'PALI POCOSOL' },
    { name: '4191', location: 'PALI LA FORTUNA' },
    { name: '4417', location: 'MAXI AGUAS ZARCAS' },
    { name: '4506', location: 'PALI AGUAS ZARCAS' },
  ],

  15: [
    { name: '721', location: 'PALI BELEN DE CARRILLO' },
    { name: '769', location: 'MAXI TAMARINDO' },
    { name: '907', location: 'PALI HOJANCHA' },
    { name: '955', location: 'PALI HUACAS' },
    { name: '3099', location: 'PALI NICOYA' },
    { name: '3135', location: 'PALI SANTA CRUZ' },
    { name: '4109', location: 'MAXI NICOYA' },
    { name: '4304', location: 'MAXI SANTA CRUZ' },
  ],

  16: [
    { name: '4092', location: 'PALI PAQUERA' },
    { name: '4093', location: 'PALI JICARAL' },
    { name: '4158', location: 'PALI NANDAYURE' },
    { name: '4198', location: 'PALI SAMARA' },
    { name: '4280', location: 'PALI COBANO' },
  ],

  18: [{ name: '4328', location: 'PALI ZARCERO' }],

  19: [
    { name: '717', location: 'MAXI NARANJO' },
    { name: '736', location: 'MXM GRECIA' },
    { name: '853', location: 'PALI TUETAL' },
    { name: '918', location: 'PALI SAN JUAN' },
    { name: '919', location: 'PALI LA GUACIMA' },
    { name: '980', location: 'PALI EL PORO' },
    { name: '982', location: 'PALI RIO SEGUNDO' },
    { name: '984', location: 'PALI LAS CAÑAS' },
    { name: '1030', location: 'PALI CANDELARIA' },
    { name: '1078', location: 'PALI COYOLAR' },
    { name: '3057', location: 'PALI GRECIA' },
    { name: '3058', location: 'PALI PUNTARENAS' },
    { name: '3068', location: 'PALI SAN RAMON' },
    { name: '3085', location: 'PALI EL ROBLE' },
    { name: '3086', location: 'PALI VILLA BONITA' },
    { name: '3095', location: 'PALI NARANJO' },
    { name: '3096', location: 'PALI ESPARZA' },
    { name: '3106', location: 'PALI LA PARADA' },
    { name: '3119', location: 'MAXI PALMARES' },
    { name: '3126', location: 'PALI OROTINA' },
    { name: '3141', location: 'PALI SARCHI' },
    { name: '4004', location: 'MAXI GRECIA' },
    { name: '4024', location: 'PALI CIRUELAS' },
    { name: '4025', location: 'PALI CHACARITA' },
    { name: '4031', location: 'MAXI SAN RAMON' },
    { name: '4047', location: 'PALI DESAMPARADOS ALAJ' },
    { name: '4075', location: 'MAXI PUNTARENAS' },
    { name: '4107', location: 'PALI EL COYOL' },
    { name: '4199', location: 'PALI BARRANCA' },
    { name: '4282', location: 'PALI EL ROBLE ALAJUELA' },
    { name: '4340', location: 'MAXI OROTINA' },
    { name: '4341', location: 'MAXI ESPARZA' },
    { name: '4429', location: 'MXM SAN RAMON' },
    { name: '4470', location: 'PALI PALMARES CENTRO' },
    { name: '4471', location: 'PALI CARRILLOS' },
    { name: '968', location: 'PALI TURRUCARES' },
  ],

  20: [],

  22: [
    { name: '3700', location: 'WM SAN SEBASTIAN' },
    { name: '3705', location: 'WM GUADALUPE' },
    { name: '3077', location: 'PALI TRES RIOS' },
    { name: '4413', location: 'WM DESAMPARADOS' },
    { name: '3702', location: 'WM CURRIDABAT' },
    { name: '3051', location: 'PALI SAUCES' },
    { name: '3097', location: 'PALI SANTA ANA' },
    { name: '3052', location: 'PALI SAN SEBASTIAN' },
    { name: '751', location: 'PALI SAN SEBASTIAN NORTE' },
    { name: '3092', location: 'PALI SAN MIGUEL DESAMPARDOS' },
    { name: '4467', location: 'PALI SAN DIEGO' },
    { name: '4135', location: 'PALI PURRAL' },
    { name: '4219', location: 'PALI PLAZA VIQUEZ' },
    { name: '4197', location: 'PALI PIEDADES' },
    { name: '924', location: 'PALI PATARRA' },
    { name: '4257', location: 'PALI PASO ANCHO' },
    { name: '4202', location: 'PALI MATA DE PLATANO' },
    { name: '3083', location: 'PALI LA VERBENA' },
    { name: '1024', location: 'PALI LA CARPINTERA' },
    { name: '3075', location: 'PALI IPIS' },
    { name: '996', location: 'PALI HIGUITO 996' },
    { name: '3061', location: 'PALI GUADALUPE' },
    { name: '1041', location: 'PALI GUADALUPE CENTRO' },
    { name: '3088', location: 'PALI FATIMA' },
    { name: '3118', location: 'PALI EL ALTO' },
    { name: '995', location: 'PALI DULCE NOMBRE TRES RIOS' },
    { name: '3072', location: 'PALI DESAMPARADOS' },
    { name: '3021', location: 'PALI CUESTA DE MORAS' },
    { name: '4218', location: 'PALI CRISTO REY' },
    { name: '4085', location: 'PALI CONCEPCION TRES RIOS' },
    { name: '3107', location: 'PALI CIUDAD COLON' },
    { name: '3066', location: 'PALI CASTELLANA' },
    { name: '3071', location: 'PALI CALLE BLANCOS' },
    { name: '4244', location: 'PALI BARRIO MEXICO' },
    { name: '4229', location: 'PALI BARRIO LA SOLEDAD' },
    { name: '4200', location: 'PALI BARRIO CUBA' },
    { name: '3055', location: 'PALI BARRIO CORDOBA' },
    { name: '743', location: 'PALI BARRIO CORAZON DE JESUS' },
    { name: '4045', location: 'PALI ASERRI' },
    { name: '3098', location: 'PALI ASERRI ABAJO' },
    { name: '834', location: 'PALI AMELIAS' },
    { name: '4243', location: 'MXM TRES RIOS CARTAGO' },
    { name: '4076', location: 'MXM SANTA ANA' },
    { name: '3028', location: 'MXM SAN GERARDO' },
    { name: '4241', location: 'MXM SAN ANTONIO DESAMPARA' },
    { name: '3034', location: 'MXM PLAZA AMERICA' },
    { name: '4325', location: 'MXM LINCOLN' },
    { name: '777', location: 'MXM GUAYABOS' },
    { name: '3024', location: 'MXM DESAMPARADOS' },
    { name: '4424', location: 'MXM CIUDAD COLON' },
    { name: '806', location: 'MP SANTA ANA' },
    { name: '930', location: 'MP LOS GUIDOS' },
    { name: '4402', location: 'MP HATILLO' },
    { name: '3048', location: 'MP GUADALUPE' },
    { name: '3900', location: 'MP EL CRUCE' },
    { name: '3022', location: 'MP CENTRO COMERCIAL HATILLO' },
    { name: '718', location: 'MP ASERRI' },
    { name: '1095', location: 'PALI MORAVIA' },
  ],
  23: [
    { name: '831', location: 'WM HEREDIA ESTE' },
    { name: '4005', location: 'MXM SANTO DOMINGO' },
    { name: '4505', location: 'MXM SAN ISIDRO' },
    { name: '3032', location: 'MXM SABANILLA' },
    { name: '3033', location: 'MXM CORONADO' },
    { name: '4216', location: 'MXM BELEN' },
    { name: '3030', location: 'MXM CARTAGO' },
    { name: '4350', location: 'MAXI SAN RAFAEL ABAJO' },
    { name: '3111', location: 'MAXI SAN RAFAEL ABAJO CENTRO' },
    { name: '733', location: 'MAXI CORONADO' },
    { name: '4283', location: 'MAXI ALAJUELITA' },
    { name: '1031', location: 'PALI VILLA NOVA' },
    { name: '790', location: 'PALI SAN JOSECITO' },
    { name: '3133', location: 'PALI SAN FELIPE' },
    { name: '3082', location: 'PALI SAN BLAS' },
    { name: '4064', location: 'PALI SAN ANTONIO CORONADO' },
    { name: '3134', location: 'PALI LOS LAGOS' },
    { name: '3104', location: 'PALI CORONADO' },
    { name: '3132', location: 'PALI CONCEPCION DE ALAJUELITA' },
    { name: '1016', location: 'PALI BETANIA' },
    { name: '3070', location: 'PALI ALAJUELITA' },
    { name: '4027', location: 'PALI SAN RAFAEL ALAJUELA' },
    { name: '4435', location: 'MAXI SAN RAFAEL ALAJUELA' },
    { name: '4214', location: 'MAXI PARAISO' },
    { name: '1053', location: 'PALI CABALLO BLANCO' },
    { name: '1117', location: 'CARTAGO ESTE' },
    { name: '3060', location: 'PALI CARTAGO' },
    { name: '3114', location: 'PALI CARTAGO CENTRO' },
    { name: '1049', location: 'PALI DESAMPARADOS OESTE' },
    { name: '1029', location: 'PALI GRAVILIAS' },
    { name: '3087', location: 'PALI LOS ANGELES' },
    { name: '3131', location: 'PALI TARAS' },
    { name: '4006', location: 'WM CARTAGO' },
    { name: '1046', location: 'WM SANTA ANA' },
    { name: '989', location: 'PALI SAN JUAN DE DIOS' },
  ],
  24: [
    { name: '4315', location: 'WM TIBAS' },
    { name: '4032', location: 'WM ESCAZU' },
    { name: '3029', location: 'MXM TIBAS' },
    { name: '3043', location: 'MXM SABANA' },
    { name: '3045', location: 'MXM ROHRMOSER' },
    { name: '3025', location: 'MXM LA GRANJA' },
    { name: '719', location: 'MXM HACIENDA VIEJA' },
    { name: '4330', location: 'MXM GUACHIPILIN' },
    { name: '3027', location: 'MXM ESCAZU' },
    { name: '4194', location: 'MAXI TIBAS' },
    { name: '4284', location: 'MAXI SAN FRANCISCO' },
    { name: '981', location: 'MAXI SAN ANTONIO ESCAZU' },
    { name: '4383', location: 'MAXI PAVAS' },
    { name: '1064', location: 'MAXI CURRIDABAT' },
    { name: '4504', location: 'PALI ZAPOTE' },
    { name: '4028', location: 'PALI TIRRASES' },
    { name: '3059', location: 'PALI TIBAS' },
    { name: '3116', location: 'PALI TIBAS EL PARQUE' },
    { name: '3074', location: 'PALI SAN FRANCISCO' },
    { name: '3062', location: 'PALI ROHRMOSER' },
    { name: '3080', location: 'PALI PAVAS' },
    { name: '3137', location: 'PALI PASEO COLON' },
    { name: '3081', location: 'PALI LOURDES' },
    { name: '3138', location: 'PALI LOMAS DEL RIO' },
    { name: '4320', location: 'PALI LLORENTE' },
    { name: '3103', location: 'PALI ESCAZU' },
    { name: '3067', location: 'PALI CURRIDABAT' },
    { name: '4425', location: 'PALI CUATRO REINAS' },
    { name: '3079', location: 'PALI COLIMA' },
    { name: '1052', location: 'PALI CINCO ESQUINAS' },
    { name: '4469', location: 'MP AGUACALIENTE' },
    { name: '776', location: 'MXM TEJAR' },
    { name: '933', location: 'PALI DULCE NOMBRE' },
    { name: '925', location: 'PALI EL MOLINO' },
    { name: '4230', location: 'PALI GRANADILLA' },
    { name: '1005', location: 'PALI GUADALUPE DE CARTAGO' },
    { name: '3100', location: 'PALI LA PITAHAYA' },
    { name: '4193', location: 'PALI SAN RAFAEL DE MONTES' },
    { name: '3122', location: 'PALI TEJAR' },
    { name: '952', location: 'PALI URUCA OESTE' },
    { name: '4449', location: 'WM LA LIMA' },
  ],

  // faArrowDownFromBracket: [],
};
