export const routes = {
  2: [
    { name: 'SUPERCENTER 736', location: 'MXM GRECIA' },
    { name: 'SUPERCENTER 717', location: 'MAXI NARANJO' },
    { name: 'SUPERCENTER 4004', location: 'MAXI GRECIA' },
    { name: 'SUPERCENTER 1030', location: 'PALI CANDELARIA' },
    { name: 'SUPERCENTER 3095', location: 'PALI NARANJO' },
    { name: 'SUPERCENTER 3141', location: 'PALI SARCHI' },
    { name: 'SUPERCENTER 3057', location: 'PALI GRECIA' },
    { name: 'SUPERCENTER 3139', location: 'PALI POAS' },
    { name: 'SUPERCENTER 979', location: 'PALI FRAIJANES' },
    { name: 'SUPERCENTER 4471', location: 'PALI CARRILLOS' },
    { name: 'SUPERCENTER 980', location: 'PALI EL PORO' },
  ],

  4: [
    { name: 'SUPERCENTER 4339', location: 'MAXI ATENAS' },
    { name: 'SUPERCENTER 3106', location: 'PALI LA PARADA' },
    { name: 'SUPERCENTER 3086', location: 'PALI VILLA BONITA' },
    { name: 'SUPERCENTER 4107', location: 'PALI EL COYOL' },
    { name: 'SUPERCENTER 4282', location: 'PALI EL ROBLE DE ALAJUELA' },
    { name: 'SUPERCENTER 4047', location: 'PALI DESAMPARADOS ALAJUELA' },
    { name: 'SUPERCENTER 4024', location: 'PALI CIRUELAS' },
    { name: 'SUPERCENTER 3125', location: 'PALI ATENAS' },
    { name: 'SUPERCENTER 968', location: 'PALI TURRUCARES' },
    { name: 'SUPERCENTER 984', location: 'PALI LAS CAÑAS' },
    { name: 'SUPERCENTER 853', location: 'PALI TUETAL' },
    { name: 'SUPERCENTER 982', location: 'PALI RIO SEGUNDO' },
    { name: 'SUPERCENTER 919', location: 'PALI LA GUACIMA' },
    { name: 'SUPERCENTER 762', location: 'PALI SABANA GRANDE' },
  ],

  5: [
    { name: 'SUPERCENTER 3701', location: 'WM HEREDIA' },
    { name: 'SUPERCENTER 4253', location: 'WM ALAJUELA' },
    { name: 'SUPERCENTER 3037', location: 'MXM SAN PABLO' },
    { name: 'SUPERCENTER 4431', location: 'MXM SAN PABLO NORTE' },
    { name: 'SUPERCENTER 4426', location: 'MXM SAN JOAQUIN' },
    { name: 'SUPERCENTER 3044', location: 'MXM PASEO DE LAS FLORES' },
    { name: 'SUPERCENTER 3036', location: 'MXM HEREDIA' },
    { name: 'SUPERCENTER 4404', location: 'MXM HEREDIA SUR' },
    { name: 'SUPERCENTER 4430', location: 'MXM BARRIO SAN JOSE' },
    { name: 'SUPERCENTER 3031', location: 'MXM ALAJUELA' },
    { name: 'SUPERCENTER 3041', location: 'MXM ALAJUELA CENTRO' },
    { name: 'SUPERCENTER 4461', location: 'MP SANTA BARBARA' },
    { name: 'SUPERCENTER 1008', location: 'MAXI SAN RAFAEL HEREDIA' },
    { name: 'SUPERCENTER 978', location: 'MAXI SAN PABLO' },
    { name: 'SUPERCENTER 4318', location: 'MAXI MERCEDES NORTE' },
    { name: 'SUPERCENTER 3901', location: 'MAXI ALAJUELA' },
    { name: 'SUPERCENTER 778', location: 'MAXI MONTECILLOS' },
    { name: 'SUPERCENTER 939', location: 'MAXI ALAJUELA ESTE' },
    { name: 'SUPERCENTER 3112', location: 'MAXI PACIFICO' },
    { name: 'SUPERCENTER 3142', location: 'PALI SANTA BARBARA' },
    { name: 'SUPERCENTER 4444', location: 'PALI SAN PEDRO DE BARVA' },
    { name: 'SUPERCENTER 4118', location: 'PALI SAN PABLO' },
    { name: 'SUPERCENTER 3120', location: 'PALI SAN JOAQUIN' },
    { name: 'SUPERCENTER 4279', location: 'PALI PARQUE CENTRAL BARVA' },
    { name: 'SUPERCENTER 3063', location: 'PALI HEREDIA' },
    { name: 'SUPERCENTER 3115', location: 'PALI HEREDIA CENTRO' },
    { name: 'SUPERCENTER 3084', location: 'PALI EL LLANO' },
    { name: 'SUPERCENTER 3091', location: 'PALI BARVA' },
    { name: 'SUPERCENTER 3121', location: 'PALI BARRIO SAN JOSE' },
    { name: 'SUPERCENTER 3056', location: 'PALI ALAJUELA' },
  ],

  7: [
    { name: 'SUPERCENTER 829', location: 'WM PEREZ ZELEDON' },
    { name: 'SUPERCENTER 4258', location: 'MAXI RIO CLARO' },
    { name: 'SUPERCENTER 4030', location: 'MAXI PEREZ ZELEDON' },
    { name: 'SUPERCENTER 966', location: 'MAXI UVITA' },
    { name: 'SUPERCENTER 737', location: 'PALI PUERTO JIMENEZ' },
    { name: 'SUPERCENTER 4063', location: 'PALI BUENOS AIRES' },
    { name: 'SUPERCENTER 1061', location: 'PALI CIUDAD CORTES' },
    { name: 'SUPERCENTER 3105', location: 'PALI CIUDAD NEILY' },
    { name: 'SUPERCENTER 4170', location: 'PALI SAN VITO COTO BRUS' },
    { name: 'SUPERCENTER 953', location: 'PALI LA CUESTA' },
    { name: 'SUPERCENTER 4003', location: 'PALI PALMAR NORTE' },
    { name: 'SUPERCENTER 3064', location: 'PALI SAN ISIDRO' },
    { name: 'SUPERCENTER 4059', location: 'PALI RIO CLARO' },
    { name: 'SUPERCENTER 1036', location: 'PALI GENERAL VIEJO' },
  ],
  8: [
    { name: 'SUPERCENTER 4099', location: 'MAXI TURRIALBA' },
    { name: 'SUPERCENTER 793', location: 'MAXI TURRIALBA NORTE' },
    { name: 'SUPERCENTER 4214', location: 'MAXI PARAISO' },
    { name: 'SUPERCENTER 1053', location: 'PALI CABALLO BLANCO' },
    { name: 'SUPERCENTER 1035', location: 'PALI SANTA ROSA TURRIALBA' },
    { name: 'SUPERCENTER 3076', location: 'PALI TURRIALBA' },
    { name: 'SUPERCENTER 4256', location: 'PALI TIERRA BLANCA' },
    { name: 'SUPERCENTER 3136', location: 'PALI COT' },
    { name: 'SUPERCENTER 749', location: 'PALI PACAYAS' },
    { name: 'SUPERCENTER 3123', location: 'PALI SANTA LUCIA' },
    { name: 'SUPERCENTER 3078', location: 'PALI PARAISO' },
    { name: 'SUPERCENTER 917', location: 'PALI CERVANTES' },
    { name: 'SUPERCENTER 967', location: 'PALI JUAN VINAS' },
    { name: 'SUPERCENTER 1000', location: 'PALI TUCURRIQUE' },
    { name: 'SUPERCENTER 786', location: 'PALI LA SUIZA' },
    { name: 'SUPERCENTER 852', location: 'PALI OROSI' },
    { name: 'SUPERCENTER 1038', location: 'PALI OREAMUNO' },
  ],
  9: [
    { name: 'SUPERCENTER 4390', location: 'MAXI PURISCAL' },
    { name: 'SUPERCENTER 3108', location: 'PALI PURISCAL' },
    { name: 'SUPERCENTER 4083', location: 'PALI TARRAZU' },
    { name: 'SUPERCENTER 950', location: 'PALI SANTA MARIA DE DOTA' },
    { name: 'SUPERCENTER 1018', location: 'PALI CORRALILLO' },
    { name: 'SUPERCENTER 4157', location: 'PALI VUELTA DE JORCO' },
    { name: 'SUPERCENTER 1063', location: 'PALI SAN PABLO LEON CORTES' },
  ],
  10: [
    { name: 'SUPERCENTER 700', location: 'WM LIBERIA' },
    { name: 'SUPERCENTER 3905', location: 'MAXI LIBERIA' },
    { name: 'SUPERCENTER 4195', location: 'MAXI CANAS' },
    { name: 'SUPERCENTER 828', location: 'MAXI UPALA' },
    { name: 'SUPERCENTER 958', location: 'MAXI PLAYAS DEL COCO' },
    { name: 'SUPERCENTER 4081', location: 'PALI BAGACES' },
    { name: 'SUPERCENTER 3065', location: 'PALI LIBERIA' },
    { name: 'SUPERCENTER 4060', location: 'PALI LA CRUZ' },
    { name: 'SUPERCENTER 4052', location: 'PALI SARDINAL' },
    { name: 'SUPERCENTER 4188', location: 'PALI SAN ROQUE LIBERIA' },
    { name: 'SUPERCENTER 4026', location: 'PALI UPALA' },
    { name: 'SUPERCENTER 3093', location: 'PALI CANAS' },
    { name: 'SUPERCENTER 1006', location: 'PALI BIJAGUA' },
    { name: 'SUPERCENTER 3124', location: 'PALI TILARAN' },
    { name: 'SUPERCENTER 1020', location: 'PALI COMUNIDAD' },
    { name: 'SUPERCENTER 4125', location: 'PALI FILADELFIA' },
    { name: 'SUPERCENTER 934', location: 'PALI GUAYABO' },
  ],

  11: [
    { name: 'SUPERCENTER 3039', location: 'MXM LIMON' },
    { name: 'SUPERCENTER 3904', location: 'MAXI LIMON' },
    { name: 'SUPERCENTER 3094', location: 'PALI LIMON' },
    { name: 'SUPERCENTER 909', location: 'PALI LIMONCITO' },
    { name: 'SUPERCENTER 994', location: 'PALI CORALES' },
    { name: 'SUPERCENTER 4181', location: 'PALI PUERTO VIEJO' },
    { name: 'SUPERCENTER 4124', location: 'PALI BATAAN' },
    { name: 'SUPERCENTER 729', location: 'PALI MATINA' },
  ],

  12: [
    { name: 'SUPERCENTER 3038', location: 'MXM GUAPILES' },
    { name: 'SUPERCENTER 4136', location: 'MAXI GUAPILES' },
    { name: 'SUPERCENTER 4369', location: 'MAXI SIQUIRRES' },
    { name: 'SUPERCENTER 965', location: 'MAXI CARIARI' },
    { name: 'SUPERCENTER 3110', location: 'PALI CARIARI' },
    { name: 'SUPERCENTER 3128', location: 'PALI GUACIMO' },
    { name: 'SUPERCENTER 3073', location: 'PALI GUAPILES' },
    { name: 'SUPERCENTER 720', location: 'PALI JIMENEZ' },
    { name: 'SUPERCENTER 711', location: 'PALI LA RITA' },
    { name: 'SUPERCENTER 961', location: 'PALI POCORA' },
    { name: 'SUPERCENTER 3143', location: 'PALI RIO FRIO' },
    { name: 'SUPERCENTER 851', location: 'PALI RIO JIMENEZ' },
    { name: 'SUPERCENTER 3101', location: 'PALI SIQUIRRES' },
    { name: 'SUPERCENTER 1001', location: 'PALI LA VIRGEN DE SARAPIQUI' },
    { name: 'SUPERCENTER 4000', location: 'PALI SARAPIQUI' },
  ],

  13: [
    { name: 'SUPERCENTER 3040', location: 'MXM JACO' },
    { name: 'SUPERCENTER 4215', location: 'MAXI QUEPOS' },
    { name: 'SUPERCENTER 4075', location: 'MAXI PUNTARENAS' },
    { name: 'SUPERCENTER 4486', location: 'MAXI PARRITA' },
    { name: 'SUPERCENTER 4029', location: 'MAXI JACO' },
    { name: 'SUPERCENTER 4341', location: 'MAXI ESPARZA' },
    { name: 'SUPERCENTER 4025', location: 'PALI CHACARITA' },
    { name: 'SUPERCENTER 4199', location: 'PALI BARRANCA' },
    { name: 'SUPERCENTER 3127', location: 'PALI QUEPOS' },
    { name: 'SUPERCENTER 3096', location: 'PALI ESPARZA' },
    { name: 'SUPERCENTER 908', location: 'PALI LA INMACULADA' },
    { name: 'SUPERCENTER 4166', location: 'PALI MIRAMAR' },
    { name: 'SUPERCENTER 3085', location: 'PALI EL ROBLE' },
    { name: 'SUPERCENTER 4128', location: 'PALI LAS JUNTAS' },
    { name: 'SUPERCENTER 3109', location: 'PALI PARRITA' },
    { name: 'SUPERCENTER 763', location: 'PALI JACO' },
    { name: 'SUPERCENTER 1062', location: 'PALI MONTEVERDE' },
    { name: 'SUPERCENTER 3058', location: 'PALI PUNTARENAS' },
  ],

  14: [
    { name: 'SUPERCENTER 768', location: 'WM CIUDAD QUESADA' },
    { name: 'SUPERCENTER 3903', location: 'MAXI CIUDAD QUESADA' },
    { name: 'SUPERCENTER 4417', location: 'MAXI AGUAS ZARCAS' },
    { name: 'SUPERCENTER 827', location: 'MAXI LA FORTUNA' },
    { name: 'SUPERCENTER 4191', location: 'PALI LA FORTUNA' },
    { name: 'SUPERCENTER 4020', location: 'PALI LOS CHILES' },
    { name: 'SUPERCENTER 3144', location: 'PALI FLORENCIA' },
    { name: 'SUPERCENTER 4506', location: 'PALI AGUAS ZARCAS' },
    { name: 'SUPERCENTER 4088', location: 'PALI POCOSOL' },
    { name: 'SUPERCENTER 781', location: 'PALI VENECIA' },
    { name: 'SUPERCENTER 785', location: 'PALI SANTA CLARA' },
    { name: 'SUPERCENTER 4021', location: 'PALI GUATUSO' },
    { name: 'SUPERCENTER 3069', location: 'PALI CIUDAD  QUESADA' },
    { name: 'SUPERCENTER 3130', location: 'PALI PITAL' },
    { name: 'SUPERCENTER 1055', location: 'PALI CIUDAD QUESADA NORTE' },
    { name: 'SUPERCENTER 1028', location: 'PALI LOS ANGELES LA FORTUNA' },
  ],

  15: [
    { name: 'SUPERCENTER 4109', location: 'MAXI NICOYA' },
    { name: 'SUPERCENTER 4304', location: 'MAXI SANTA CRUZ' },
    { name: 'SUPERCENTER 769', location: 'MAXI TAMARINDO' },
    { name: 'SUPERCENTER 3099', location: 'PALI NICOYA' },
    { name: 'SUPERCENTER 3135', location: 'PALI SANTA CRUZ' },
    { name: 'SUPERCENTER 721', location: 'PALI BELEN DE CARRILLO' },
    { name: 'SUPERCENTER 955', location: 'PALI HUACAS' },
    { name: 'SUPERCENTER 907', location: 'PALI HOJANCHA' },
  ],

  16: [
    { name: 'SUPERCENTER 4280', location: 'PALI COBANO' },
    { name: 'SUPERCENTER 4093', location: 'PALI JICARAL' },
    { name: 'SUPERCENTER 4158', location: 'PALI NANDAYURE' },
    { name: 'SUPERCENTER 4092', location: 'PALI PAQUERA' },
    { name: 'SUPERCENTER 4198', location: 'PALI SAMARA' },
  ],

  18: [
    { name: 'SUPERCENTER 4429', location: 'MXM SAN RAMON' },
    { name: 'SUPERCENTER 4340', location: 'MAXI OROTINA' },
    { name: 'SUPERCENTER 4031', location: 'MAXI SAN RAMON' },
    { name: 'SUPERCENTER 3119', location: 'MAXI PALMARES' },
    { name: 'SUPERCENTER 3126', location: 'PALI OROTINA' },
    { name: 'SUPERCENTER 918', location: 'PALI SAN JUAN' },
    { name: 'SUPERCENTER 4328', location: 'PALI ZARCERO' },
    { name: 'SUPERCENTER 3068', location: 'PALI SAN RAMON' },
    { name: 'SUPERCENTER 4470', location: 'PALI PALMARES CENTRO' },
  ],

  20: [
    { name: 'SUPERCENTER 988', location: 'MAXI LAGUNILLA' },
    { name: 'SUPERCENTER 3089', location: 'PALI AURORA' },
    { name: 'SUPERCENTER 3090', location: 'PALI BELEN' },
    { name: 'SUPERCENTER 3053', location: 'PALI STO.DOMINGO' },
    { name: 'SUPERCENTER 4261', location: 'PALI SAN MIGUEL SANTO DOMINGO' },
    { name: 'SUPERCENTER 4084', location: 'PALI SAN ISIDRO HEREDIA' },
    { name: 'SUPERCENTER 4281', location: 'PALI MERCEDES SUR' },
    { name: 'SUPERCENTER 3145', location: 'PALI SAN RAFAEL HEREDIA' },
    { name: 'SUPERCENTER 1026', location: 'PALI EL ROBLE SANTA BARBARA' },
    { name: 'SUPERCENTER 1015', location: 'PALI SAN LUIS SANTO DOMINGO' },
    { name: 'SUPERCENTER 3102', location: 'PALI UNICENTRO' },
    { name: 'SUPERCENTER 990', location: 'PALI SANTA ROSA' },
    { name: 'SUPERCENTER 1012', location: 'PALI MIRAFLORES' },
  ],

  22: [
    { name: 'SUPERCENTER 4315', location: 'WM TIBAS' },
    { name: 'SUPERCENTER 3700', location: 'WM SAN SEBASTIAN' },
    { name: 'SUPERCENTER 4449', location: 'WM LA LIMA' },
    { name: 'SUPERCENTER 3705', location: 'WM GUADALUPE' },
    { name: 'SUPERCENTER 4032', location: 'WM ESCAZU' },
    { name: 'SUPERCENTER 4413', location: 'WM DESAMPARADOS' },
    { name: 'SUPERCENTER 3702', location: 'WM CURRIDABAT' },
    { name: 'SUPERCENTER 4006', location: 'WM CARTAGO' },
    { name: 'SUPERCENTER 4504', location: 'PALI ZAPOTE' },
    { name: 'SUPERCENTER 1031', location: 'PALI VILLA NOVA' },
    { name: 'SUPERCENTER 952', location: 'PALI URUCA OESTE' },
    { name: 'SUPERCENTER 3077', location: 'PALI TRES RIOS' },
    { name: 'SUPERCENTER 4028', location: 'PALI TIRRASES' },
    { name: 'SUPERCENTER 3059', location: 'PALI TIBAS' },
    { name: 'SUPERCENTER 3116', location: 'PALI TIBAS EL PARQUE' },
    { name: 'SUPERCENTER 3122', location: 'PALI TEJAR' },
    { name: 'SUPERCENTER 3131', location: 'PALI TARAS' },
    { name: 'SUPERCENTER 3051', location: 'PALI SAUCES' },
    { name: 'SUPERCENTER 3097', location: 'PALI SANTA ANA' },
    { name: 'SUPERCENTER 3052', location: 'PALI SAN SEBASTIAN' },
    { name: 'SUPERCENTER 751', location: 'PALI SAN SEBASTIAN NORTE' },
    { name: 'SUPERCENTER 4193', location: 'PALI SAN RAFAEL DE MONTES' },
    { name: 'SUPERCENTER 3092', location: 'PALI SAN MIGUEL DESAMPARDOS' },
    { name: 'SUPERCENTER 989', location: 'PALI SAN JUAN DE DIOS' },
    { name: 'SUPERCENTER 790', location: 'PALI SAN JOSECITO' },
    { name: 'SUPERCENTER 3074', location: 'PALI SAN FRANCISCO' },
    { name: 'SUPERCENTER 3133', location: 'PALI SAN FELIPE' },
    { name: 'SUPERCENTER 4467', location: 'PALI SAN DIEGO' },
    { name: 'SUPERCENTER 3082', location: 'PALI SAN BLAS' },
    { name: 'SUPERCENTER 4064', location: 'PALI SAN ANTONIO CORONADO' },
    { name: 'SUPERCENTER 3062', location: 'PALI ROHRMOSER' },
    { name: 'SUPERCENTER 4135', location: 'PALI PURRAL' },
    { name: 'SUPERCENTER 4219', location: 'PALI PLAZA VIQUEZ' },
    { name: 'SUPERCENTER 4197', location: 'PALI PIEDADES' },
    { name: 'SUPERCENTER 3080', location: 'PALI PAVAS' },
    { name: 'SUPERCENTER 924', location: 'PALI PATARRA' },
    { name: 'SUPERCENTER 4257', location: 'PALI PASO ANCHO' },
    { name: 'SUPERCENTER 3137', location: 'PALI PASEO COLON' },
    { name: 'SUPERCENTER 4202', location: 'PALI MATA DE PLATANO' },
    { name: 'SUPERCENTER 3081', location: 'PALI LOURDES' },
    { name: 'SUPERCENTER 3087', location: 'PALI LOS ANGELES' },
    { name: 'SUPERCENTER 3138', location: 'PALI LOMAS DEL RIO' },
    { name: 'SUPERCENTER 4320', location: 'PALI LLORENTE' },
    { name: 'SUPERCENTER 3083', location: 'PALI LA VERBENA' },
    { name: 'SUPERCENTER 3100', location: 'PALI LA PITAHAYA' },
    { name: 'SUPERCENTER 1024', location: 'PALI LA CARPINTERA' },
    { name: 'SUPERCENTER 3075', location: 'PALI IPIS' },
    { name: 'SUPERCENTER 996', location: 'PALI HIGUITO 996' },
    { name: 'SUPERCENTER 3061', location: 'PALI GUADALUPE' },
    { name: 'SUPERCENTER 1005', location: 'PALI GUADALUPE DE CARTAGO' },
    { name: 'SUPERCENTER 1041', location: 'PALI GUADALUPE CENTRO' },
    { name: 'SUPERCENTER 1029', location: 'PALI GRAVILIAS' },
    { name: 'SUPERCENTER 4230', location: 'PALI GRANADILLA' },
    { name: 'SUPERCENTER 3088', location: 'PALI FATIMA' },
    { name: 'SUPERCENTER 3103', location: 'PALI ESCAZU' },
    { name: 'SUPERCENTER 925', location: 'PALI EL MOLINO' },
    { name: 'SUPERCENTER 3118', location: 'PALI EL ALTO' },
    { name: 'SUPERCENTER 995', location: 'PALI DULCE NOMBRE TRES RIOS' },
    { name: 'SUPERCENTER 933', location: 'PALI DULCE NOMBRE' },
    { name: 'SUPERCENTER 3072', location: 'PALI DESAMPARADOS' },
    { name: 'SUPERCENTER 1049', location: 'PALI DESAMPARADOS OESTE' },
    { name: 'SUPERCENTER 3113', location: 'PALI DESAMPARADOS CENTRO' },
    { name: 'SUPERCENTER 3067', location: 'PALI CURRIDABAT' },
    { name: 'SUPERCENTER 3021', location: 'PALI CUESTA DE MORAS' },
    { name: 'SUPERCENTER 4425', location: 'PALI CUATRO REINAS' },
    { name: 'SUPERCENTER 4218', location: 'PALI CRISTO REY' },
    { name: 'SUPERCENTER 3104', location: 'PALI CORONADO' },
    { name: 'SUPERCENTER 4085', location: 'PALI CONCEPCION TRES RIOS' },
    { name: 'SUPERCENTER 3132', location: 'PALI CONCEPCION DE ALAJUELITA' },
    { name: 'SUPERCENTER 3079', location: 'PALI COLIMA' },
    { name: 'SUPERCENTER 3107', location: 'PALI CIUDAD COLON' },
    { name: 'SUPERCENTER 1052', location: 'PALI CINCO ESQUINAS' },
    { name: 'SUPERCENTER 3066', location: 'PALI CASTELLANA' },
    { name: 'SUPERCENTER 3060', location: 'PALI CARTAGO' },
    { name: 'SUPERCENTER 3114', location: 'PALI CARTAGO CENTRO' },
    { name: 'WAL-MART STORE 3071', location: 'PALI CALLE BLANCOS' },
    { name: 'SUPERCENTER 1016', location: 'PALI BETANIA' },
    { name: 'SUPERCENTER 4244', location: 'PALI BARRIO MEXICO' },
    { name: 'SUPERCENTER 4229', location: 'PALI BARRIO LA SOLEDAD' },
    { name: 'SUPERCENTER 4200', location: 'PALI BARRIO CUBA' },
    { name: 'SUPERCENTER 3055', location: 'PALI BARRIO CORDOBA' },
    { name: 'SUPERCENTER 743', location: 'PALI BARRIO CORAZON DE JESUS' },
    { name: 'SUPERCENTER 4045', location: 'PALI ASERRI' },
    { name: 'SUPERCENTER 3098', location: 'PALI ASERRI ABAJO' },
    { name: 'SUPERCENTER 834', location: 'PALI AMELIAS' },
    { name: 'SUPERCENTER 3070', location: 'PALI ALAJUELITA' },
    { name: 'SUPERCENTER 4243', location: 'MXM TRES RIOS CARTAGO' },
    { name: 'SUPERCENTER 3029', location: 'MXM TIBAS' },
    { name: 'SUPERCENTER 776', location: 'MXM TEJAR' },
    { name: 'SUPERCENTER 4076', location: 'MXM SANTA ANA' },
    { name: 'SUPERCENTER 3028', location: 'MXM SAN GERARDO' },
    { name: 'SUPERCENTER 4241', location: 'MXM SAN ANTONIO DESAMPARA' },
    { name: 'SUPERCENTER 3032', location: 'MXM SABANILLA' },
    { name: 'SUPERCENTER 3043', location: 'MXM SABANA' },
    { name: 'SUPERCENTER 3045', location: 'MXM ROHRMOSER' },
    { name: 'SUPERCENTER 3034', location: 'MXM PLAZA AMERICA' },
    { name: 'SUPERCENTER 4325', location: 'MXM LINCOLN' },
    { name: 'SUPERCENTER 3025', location: 'MXM LA GRANJA' },
    { name: 'SUPERCENTER 719', location: 'MXM HACIENDA VIEJA' },
    { name: 'SUPERCENTER 777', location: 'MXM GUAYABOS' },
    { name: 'SUPERCENTER 4330', location: 'MXM GUACHIPILIN' },
    { name: 'SUPERCENTER 3027', location: 'MXM ESCAZU' },
    { name: 'SUPERCENTER 3024', location: 'MXM DESAMPARADOS' },
    { name: 'SUPERCENTER 3033', location: 'MXM CORONADO' },
    { name: 'SUPERCENTER 4424', location: 'MXM CIUDAD COLON' },
    { name: 'SUPERCENTER 3030', location: 'MXM CARTAGO' },
    { name: 'SUPERCENTER 4194', location: 'MP TIBAS' },
    { name: 'SUPERCENTER 806', location: 'MP SANTA ANA' },
    { name: 'SUPERCENTER 4350', location: 'MP SAN RAFAEL ABAJO' },
    { name: 'SUPERCENTER 3111', location: 'MP SAN RAFAEL ABAJO CENTRO' },
    { name: 'SUPERCENTER 4284', location: 'MP SAN FRANCISCO' },
    { name: 'SUPERCENTER 981', location: 'MP SAN ANTONIO ESCAZU' },
    { name: 'SUPERCENTER 4383', location: 'MP PAVAS' },
    { name: 'SUPERCENTER 930', location: 'MP LOS GUIDOS' },
    { name: 'SUPERCENTER 4402', location: 'MP HATILLO' },
    { name: 'SUPERCENTER 3048', location: 'MP GUADALUPE' },
    { name: 'SUPERCENTER 3900', location: 'MP EL CRUCE' },
    { name: 'SUPERCENTER 733', location: 'MP CORONADO' },
    { name: 'SUPERCENTER 3022', location: 'MP CENTRO COMERCIAL HATILLO' },
    { name: 'SUPERCENTER 718', location: 'MP ASERRI' },
    { name: 'SUPERCENTER 4283', location: 'MP ALAJUELITA' },
    { name: 'SUPERCENTER 4469', location: 'MP AGUACALIENTE' },
    { name: 'SUPERCENTER 1064', location: 'MAXI CURRIDABAT (PLAZA CRISTAL)' },
    {name: 'SUPERCENTER 738', location: 'PALI TOBOSI' },
    {name: 'SUPERCENTER 4432', location: 'MAXI OREAMUNO' },
  ],

  23: [
    { name: 'SUPERCENTE 831', location: 'WM HEREDIA ESTE' },
    { name: 'SUPERCENTE 4005', location: 'MXM SANTO DOMINGO' },
    { name: 'SUPERCENTE 4505', location: 'MXM SAN ISIDRO' },
    { name: 'SUPERCENTE 3032', location: 'MXM SABANILLA' },
    { name: 'SUPERCENTE 3024', location: 'MXM DESAMPARADOS' },
    { name: 'SUPERCENTE 3033', location: 'MXM CORONADO' },
    { name: 'SUPERCENTE 4216', location: 'MXM BELEN' },
    { name: 'SUPERCENTE 4424', location: 'MXM CIUDAD COLON' },
    { name: 'SUPERCENTE 3030', location: 'MXM CARTAGO' },
    { name: 'SUPERCENTE 4350', location: 'MAXI SAN RAFAEL ABAJO' },
    { name: 'SUPERCENTE 3111', location: 'MAXI SAN RAFAEL ABAJO CENTRO' },
    { name: 'SUPERCENTE 930', location: 'MAXI LOS GUIDOS' },
    { name: 'SUPERCENTE 3900', location: 'MAXI EL CRUCE' },
    { name: 'SUPERCENTE 733', location: 'MAXI CORONADO' },
    { name: 'SUPERCENTE 4283', location: 'MAXI ALAJUELITA' },
    { name: 'SUPERCENTE 1031', location: 'PALI VILLA NOVA' },
    { name: 'SUPERCENTE 3092', location: 'PALI SAN MIGUEL DESAMPARDOS' },
    { name: 'SUPERCENTE 790', location: 'PALI SAN JOSECITO' },
    { name: 'SUPERCENTE 3133', location: 'PALI SAN FELIPE' },
    { name: 'SUPERCENTE 3082', location: 'PALI SAN BLAS' },
    { name: 'SUPERCENTE 4064', location: 'PALI SAN ANTONIO CORONADO' },
    { name: 'SUPERCENTE 3134', location: 'PALI LOS LAGOS' },
    { name: 'SUPERCENTE 996', location: 'PALI HIGUITO 996' },
    { name: 'SUPERCENTE 3072', location: 'PALI DESAMPARADOS' },
    { name: 'SUPERCENTE 3113', location: 'PALI DESAMPARADOS CENTRO' },
    { name: 'SUPERCENTE 3104', location: 'PALI CORONADO' },
    { name: 'SUPERCENTE 3132', location: 'PALI CONCEPCION DE ALAJUELITA' },
    { name: 'SUPERCENTE 1016', location: 'PALI BETANIA' },
    { name: 'SUPERCENTE 3070', location: 'PALI ALAJUELITA' },
    { name: 'SUPERCENTE 4027', location: 'PALI SAN RAFAEL ALAJUELA' },
    { name: 'SUPERCENTE 4435', location: 'MAXI SAN RAFAEL ALAJUELA' },
  ],

  24: [
    { name: 'SUPERCENTER 4315', location: 'WM TIBAS' },
    { name: 'SUPERCENTER 4032', location: 'WM ESCAZU' },
    { name: 'SUPERCENTER 3702', location: 'WM CURRIDABAT' },
    { name: 'SUPERCENTER 3029', location: 'MXM TIBAS' },
    { name: 'SUPERCENTER 4241', location: 'MXM SAN ANTONIO DESAMP' },
    { name: 'SUPERCENTER 3043', location: 'MXM SABANA' },
    { name: 'SUPERCENTER 3045', location: 'MXM ROHRMOSER' },
    { name: 'SUPERCENTER 3025', location: 'MXM LA GRANJA' },
    { name: 'SUPERCENTER 719', location: 'MXM HACIENDA VIEJA' },
    { name: 'SUPERCENTER 4330', location: 'MXM GUACHIPILIN' },
    { name: 'SUPERCENTER 3027', location: 'MXM ESCAZU' },
    { name: 'SUPERCENTER 4194', location: 'MAXI TIBAS' },
    { name: 'SUPERCENTER 4284', location: 'MAXI SAN FRANCISCO' },
    { name: 'SUPERCENTER 981', location: 'MAXI SAN ANTONIO ESCAZU' },
    { name: 'SUPERCENTER 4383', location: 'MAXI PAVAS' },
    { name: 'SUPERCENTER 1064', location: 'MAXI CURRIDABAT' },
    { name: 'SUPERCENTER 4504', location: 'PALI ZAPOTE' },
    { name: 'SUPERCENTER 4028', location: 'PALI TIRRASES' },
    { name: 'SUPERCENTER 3059', location: 'PALI TIBAS' },
    { name: 'SUPERCENTER 3116', location: 'PALI TIBAS EL PARQUE' },
    { name: 'SUPERCENTER 3051', location: 'PALI SAUCES' },
    { name: 'SUPERCENTER 3074', location: 'PALI SAN FRANCISCO' },
    { name: 'SUPERCENTER 3062', location: 'PALI ROHRMOSER' },
    { name: 'SUPERCENTER 3080', location: 'PALI PAVAS' },
    { name: 'SUPERCENTER 924', location: 'PALI PATARRA' },
    { name: 'SUPERCENTER 3137', location: 'PALI PASEO COLON' },
    { name: 'SUPERCENTER 3081', location: 'PALI LOURDES' },
    { name: 'SUPERCENTER 3138', location: 'PALI LOMAS DEL RIO' },
    { name: 'SUPERCENTER 4320', location: 'PALI LLORENTE' },
    { name: 'SUPERCENTER 3088', location: 'PALI FATIMA' },
    { name: 'SUPERCENTER 3103', location: 'PALI ESCAZU' },
    { name: 'SUPERCENTER 3067', location: 'PALI CURRIDABAT' },
    { name: 'SUPERCENTER 4425', location: 'PALI CUATRO REINAS' },
    { name: 'SUPERCENTER 3079', location: 'PALI COLIMA' },
    { name: 'SUPERCENTER 1052', location: 'PALI CINCO ESQUINAS' },
  ],

  unProcessed: [],
};
